# https://github.com/go-flutter-desktop/hover
include ../../boilerplate/tool/tools.mk

override LIB_NAME=hover
override LIB_ORG=go-flutter-desktop
override LIB_TAG=v0.39.0
override LIB_BIN_NAME=$(LIB_NAME)

