# git include
include ../../../../../packages/boilerplate/help.mk
include ../../../../../packages/boilerplate/flu.mk

override FLU_SAMPLE_NAME =
override FLU_LIB_NAME =

# to get the example running follow the steps:
# 0. make flu-gen-lang
# 1. make flu-gen-lang-dart
# 2. make flu-web-run

## Print all settings
print: ## print
	@echo -- REPO -- 
	@echo REPOSITORY: $(REPOSITORY)
	@echo
	
	$(MAKE) flu-print
