# git include
include ../../../../boilerplate/core/help.mk
include ../../../../boilerplate/core/os.mk
include ../../../../boilerplate/core/flu.mk
include ../../../../boilerplate/core/srv.mk

override FLU_SAMPLE_NAME = client
override FLU_LIB_NAME = client

