// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MinioComponent struct {
	MinioAccesskey       *ConfigVal `protobuf:"bytes,1,opt,name=minio_accesskey,json=minioAccesskey,proto3" json:"minio_accesskey,omitempty"`
	MinioSecretkey       *ConfigVal `protobuf:"bytes,2,opt,name=minio_secretkey,json=minioSecretkey,proto3" json:"minio_secretkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MinioComponent) Reset()         { *m = MinioComponent{} }
func (m *MinioComponent) String() string { return proto.CompactTextString(m) }
func (*MinioComponent) ProtoMessage()    {}
func (*MinioComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{0}
}

func (m *MinioComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinioComponent.Unmarshal(m, b)
}
func (m *MinioComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinioComponent.Marshal(b, m, deterministic)
}
func (m *MinioComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinioComponent.Merge(m, src)
}
func (m *MinioComponent) XXX_Size() int {
	return xxx_messageInfo_MinioComponent.Size(m)
}
func (m *MinioComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_MinioComponent.DiscardUnknown(m)
}

var xxx_messageInfo_MinioComponent proto.InternalMessageInfo

func (m *MinioComponent) GetMinioAccesskey() *ConfigVal {
	if m != nil {
		return m.MinioAccesskey
	}
	return nil
}

func (m *MinioComponent) GetMinioSecretkey() *ConfigVal {
	if m != nil {
		return m.MinioSecretkey
	}
	return nil
}

type MaintemplateComponent struct {
	MinioAccesskey       *ConfigVal `protobuf:"bytes,1,opt,name=minio_accesskey,json=minioAccesskey,proto3" json:"minio_accesskey,omitempty"`
	MinioSecretkey       *ConfigVal `protobuf:"bytes,2,opt,name=minio_secretkey,json=minioSecretkey,proto3" json:"minio_secretkey,omitempty"`
	MinioLocation        *ConfigVal `protobuf:"bytes,3,opt,name=minio_location,json=minioLocation,proto3" json:"minio_location,omitempty"`
	MinioTimeout         *ConfigVal `protobuf:"bytes,4,opt,name=minio_timeout,json=minioTimeout,proto3" json:"minio_timeout,omitempty"`
	MinioSsl             *ConfigVal `protobuf:"bytes,5,opt,name=minio_ssl,json=minioSsl,proto3" json:"minio_ssl,omitempty"`
	MinioEnckey          *ConfigVal `protobuf:"bytes,6,opt,name=minio_enckey,json=minioEnckey,proto3" json:"minio_enckey,omitempty"`
	Minioendpoint        *ConfigVal `protobuf:"bytes,7,opt,name=minioendpoint,proto3" json:"minioendpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MaintemplateComponent) Reset()         { *m = MaintemplateComponent{} }
func (m *MaintemplateComponent) String() string { return proto.CompactTextString(m) }
func (*MaintemplateComponent) ProtoMessage()    {}
func (*MaintemplateComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{1}
}

func (m *MaintemplateComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaintemplateComponent.Unmarshal(m, b)
}
func (m *MaintemplateComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaintemplateComponent.Marshal(b, m, deterministic)
}
func (m *MaintemplateComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaintemplateComponent.Merge(m, src)
}
func (m *MaintemplateComponent) XXX_Size() int {
	return xxx_messageInfo_MaintemplateComponent.Size(m)
}
func (m *MaintemplateComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_MaintemplateComponent.DiscardUnknown(m)
}

var xxx_messageInfo_MaintemplateComponent proto.InternalMessageInfo

func (m *MaintemplateComponent) GetMinioAccesskey() *ConfigVal {
	if m != nil {
		return m.MinioAccesskey
	}
	return nil
}

func (m *MaintemplateComponent) GetMinioSecretkey() *ConfigVal {
	if m != nil {
		return m.MinioSecretkey
	}
	return nil
}

func (m *MaintemplateComponent) GetMinioLocation() *ConfigVal {
	if m != nil {
		return m.MinioLocation
	}
	return nil
}

func (m *MaintemplateComponent) GetMinioTimeout() *ConfigVal {
	if m != nil {
		return m.MinioTimeout
	}
	return nil
}

func (m *MaintemplateComponent) GetMinioSsl() *ConfigVal {
	if m != nil {
		return m.MinioSsl
	}
	return nil
}

func (m *MaintemplateComponent) GetMinioEnckey() *ConfigVal {
	if m != nil {
		return m.MinioEnckey
	}
	return nil
}

func (m *MaintemplateComponent) GetMinioendpoint() *ConfigVal {
	if m != nil {
		return m.Minioendpoint
	}
	return nil
}

type GcpComponent struct {
	GcpUser              *ConfigVal `protobuf:"bytes,1,opt,name=gcp_user,json=gcpUser,proto3" json:"gcp_user,omitempty"`
	GcpProject           *ConfigVal `protobuf:"bytes,2,opt,name=gcp_project,json=gcpProject,proto3" json:"gcp_project,omitempty"`
	GkeCluster           *ConfigVal `protobuf:"bytes,3,opt,name=gke_cluster,json=gkeCluster,proto3" json:"gke_cluster,omitempty"`
	GkeZone              *ConfigVal `protobuf:"bytes,4,opt,name=gke_zone,json=gkeZone,proto3" json:"gke_zone,omitempty"`
	GkeEmail             *ConfigVal `protobuf:"bytes,5,opt,name=gke_email,json=gkeEmail,proto3" json:"gke_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GcpComponent) Reset()         { *m = GcpComponent{} }
func (m *GcpComponent) String() string { return proto.CompactTextString(m) }
func (*GcpComponent) ProtoMessage()    {}
func (*GcpComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{2}
}

func (m *GcpComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GcpComponent.Unmarshal(m, b)
}
func (m *GcpComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GcpComponent.Marshal(b, m, deterministic)
}
func (m *GcpComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GcpComponent.Merge(m, src)
}
func (m *GcpComponent) XXX_Size() int {
	return xxx_messageInfo_GcpComponent.Size(m)
}
func (m *GcpComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_GcpComponent.DiscardUnknown(m)
}

var xxx_messageInfo_GcpComponent proto.InternalMessageInfo

func (m *GcpComponent) GetGcpUser() *ConfigVal {
	if m != nil {
		return m.GcpUser
	}
	return nil
}

func (m *GcpComponent) GetGcpProject() *ConfigVal {
	if m != nil {
		return m.GcpProject
	}
	return nil
}

func (m *GcpComponent) GetGkeCluster() *ConfigVal {
	if m != nil {
		return m.GkeCluster
	}
	return nil
}

func (m *GcpComponent) GetGkeZone() *ConfigVal {
	if m != nil {
		return m.GkeZone
	}
	return nil
}

func (m *GcpComponent) GetGkeEmail() *ConfigVal {
	if m != nil {
		return m.GkeEmail
	}
	return nil
}

type JwtComponent struct {
	PrivateKey           *ConfigVal `protobuf:"bytes,1,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey            *ConfigVal `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JwtComponent) Reset()         { *m = JwtComponent{} }
func (m *JwtComponent) String() string { return proto.CompactTextString(m) }
func (*JwtComponent) ProtoMessage()    {}
func (*JwtComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{3}
}

func (m *JwtComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtComponent.Unmarshal(m, b)
}
func (m *JwtComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtComponent.Marshal(b, m, deterministic)
}
func (m *JwtComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtComponent.Merge(m, src)
}
func (m *JwtComponent) XXX_Size() int {
	return xxx_messageInfo_JwtComponent.Size(m)
}
func (m *JwtComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtComponent.DiscardUnknown(m)
}

var xxx_messageInfo_JwtComponent proto.InternalMessageInfo

func (m *JwtComponent) GetPrivateKey() *ConfigVal {
	if m != nil {
		return m.PrivateKey
	}
	return nil
}

func (m *JwtComponent) GetPublicKey() *ConfigVal {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type WorkflowComponent struct {
	GithubSha            *ConfigVal `protobuf:"bytes,2,opt,name=github_sha,json=githubSha,proto3" json:"github_sha,omitempty"`
	GithubRef            *ConfigVal `protobuf:"bytes,3,opt,name=github_ref,json=githubRef,proto3" json:"github_ref,omitempty"`
	Project              *ConfigVal `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	RegistryHostname     *ConfigVal `protobuf:"bytes,5,opt,name=registry_hostname,json=registryHostname,proto3" json:"registry_hostname,omitempty"`
	Url                  *ConfigVal `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	Locales              *ConfigVal `protobuf:"bytes,7,opt,name=locales,proto3" json:"locales,omitempty"`
	FlutterChannel       *ConfigVal `protobuf:"bytes,8,opt,name=flutter_channel,json=flutterChannel,proto3" json:"flutter_channel,omitempty"`
	ReleaseChannel       *ConfigVal `protobuf:"bytes,9,opt,name=release_channel,json=releaseChannel,proto3" json:"release_channel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WorkflowComponent) Reset()         { *m = WorkflowComponent{} }
func (m *WorkflowComponent) String() string { return proto.CompactTextString(m) }
func (*WorkflowComponent) ProtoMessage()    {}
func (*WorkflowComponent) Descriptor() ([]byte, []int) {
	return fileDescriptor_3eaf2c85e69e9ea4, []int{4}
}

func (m *WorkflowComponent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowComponent.Unmarshal(m, b)
}
func (m *WorkflowComponent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowComponent.Marshal(b, m, deterministic)
}
func (m *WorkflowComponent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowComponent.Merge(m, src)
}
func (m *WorkflowComponent) XXX_Size() int {
	return xxx_messageInfo_WorkflowComponent.Size(m)
}
func (m *WorkflowComponent) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowComponent.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowComponent proto.InternalMessageInfo

func (m *WorkflowComponent) GetGithubSha() *ConfigVal {
	if m != nil {
		return m.GithubSha
	}
	return nil
}

func (m *WorkflowComponent) GetGithubRef() *ConfigVal {
	if m != nil {
		return m.GithubRef
	}
	return nil
}

func (m *WorkflowComponent) GetProject() *ConfigVal {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *WorkflowComponent) GetRegistryHostname() *ConfigVal {
	if m != nil {
		return m.RegistryHostname
	}
	return nil
}

func (m *WorkflowComponent) GetUrl() *ConfigVal {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *WorkflowComponent) GetLocales() *ConfigVal {
	if m != nil {
		return m.Locales
	}
	return nil
}

func (m *WorkflowComponent) GetFlutterChannel() *ConfigVal {
	if m != nil {
		return m.FlutterChannel
	}
	return nil
}

func (m *WorkflowComponent) GetReleaseChannel() *ConfigVal {
	if m != nil {
		return m.ReleaseChannel
	}
	return nil
}

func init() {
	proto.RegisterType((*MinioComponent)(nil), "config.MinioComponent")
	proto.RegisterType((*MaintemplateComponent)(nil), "config.MaintemplateComponent")
	proto.RegisterType((*GcpComponent)(nil), "config.GcpComponent")
	proto.RegisterType((*JwtComponent)(nil), "config.JwtComponent")
	proto.RegisterType((*WorkflowComponent)(nil), "config.WorkflowComponent")
}

func init() { proto.RegisterFile("config.proto", fileDescriptor_3eaf2c85e69e9ea4) }

var fileDescriptor_3eaf2c85e69e9ea4 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0x4f, 0x8b, 0x13, 0x31,
	0x14, 0xc0, 0xe9, 0x56, 0xfb, 0xe7, 0xb5, 0xee, 0xda, 0x80, 0x30, 0x78, 0x92, 0x7a, 0x11, 0x94,
	0xb2, 0x54, 0x51, 0x51, 0x10, 0xb4, 0x2c, 0x8a, 0xeb, 0x82, 0xec, 0xfa, 0x07, 0xf6, 0x12, 0xd2,
	0xf8, 0x3a, 0x8d, 0x93, 0x49, 0x86, 0x24, 0xe3, 0x52, 0x8f, 0x9e, 0xfc, 0x18, 0x7e, 0x02, 0x3f,
	0xa3, 0x64, 0x92, 0xb1, 0x5e, 0x32, 0x57, 0x4f, 0xc3, 0xbc, 0xfc, 0x7e, 0x99, 0x97, 0xf7, 0xde,
	0x04, 0xa6, 0x5c, 0xab, 0x8d, 0xc8, 0x17, 0x95, 0xd1, 0x4e, 0x93, 0x41, 0x78, 0xbb, 0x7d, 0xb4,
	0x66, 0x16, 0x9b, 0x50, 0x58, 0x98, 0xff, 0xec, 0xc1, 0xe1, 0x99, 0x50, 0x42, 0xaf, 0x74, 0x59,
	0x69, 0x85, 0xca, 0x91, 0x67, 0x70, 0x54, 0xfa, 0x08, 0x65, 0x9c, 0xa3, 0xb5, 0x05, 0xee, 0xb2,
	0xde, 0x9d, 0xde, 0xbd, 0xc9, 0x72, 0xb6, 0x88, 0x7b, 0xae, 0x9a, 0xc7, 0x27, 0x26, 0xcf, 0x0f,
	0x1b, 0xf2, 0x65, 0x0b, 0xee, 0x5d, 0x8b, 0xdc, 0xa0, 0xf3, 0xee, 0x41, 0xb7, 0x7b, 0xd1, 0x82,
	0xf3, 0x5f, 0x7d, 0xb8, 0x75, 0xc6, 0x84, 0x72, 0x58, 0x56, 0x92, 0x39, 0xfc, 0xef, 0x19, 0x91,
	0xa7, 0x10, 0x22, 0x54, 0x6a, 0xce, 0x9c, 0xd0, 0x2a, 0xeb, 0xa7, 0xd4, 0x1b, 0x0d, 0xf8, 0x2e,
	0x72, 0xe4, 0x31, 0x84, 0x00, 0x75, 0xa2, 0x44, 0x5d, 0xbb, 0xec, 0x5a, 0x4a, 0x9c, 0x36, 0xdc,
	0x87, 0x80, 0x91, 0x05, 0x8c, 0x63, 0xb6, 0x56, 0x66, 0xd7, 0x53, 0xce, 0x28, 0xe4, 0x69, 0x25,
	0x79, 0x04, 0xc1, 0xa7, 0xa8, 0xb8, 0x3f, 0xda, 0x20, 0xa5, 0x4c, 0x1a, 0xec, 0xa4, 0xa1, 0xc8,
	0x93, 0x98, 0x1d, 0xaa, 0x2f, 0x95, 0x16, 0xca, 0x65, 0xc3, 0xee, 0x63, 0xb5, 0xdc, 0xfc, 0xc7,
	0x01, 0x4c, 0x5f, 0xf3, 0x6a, 0xdf, 0x99, 0x07, 0x30, 0xca, 0x79, 0x45, 0x6b, 0x8b, 0x26, 0xdd,
	0x92, 0x61, 0xce, 0xab, 0x8f, 0x16, 0x0d, 0x59, 0xc2, 0xc4, 0xd3, 0x95, 0xd1, 0x5f, 0x91, 0xbb,
	0x74, 0x1f, 0x20, 0xe7, 0xd5, 0xfb, 0x00, 0x35, 0x4e, 0x81, 0x94, 0xcb, 0xda, 0x3a, 0x34, 0xe9,
	0x06, 0x40, 0x5e, 0xe0, 0x2a, 0x40, 0x4d, 0x56, 0x05, 0xd2, 0xef, 0x5a, 0x61, 0xba, 0xf0, 0xc3,
	0xbc, 0xc0, 0x4b, 0xad, 0xd0, 0xd7, 0xdc, 0xd3, 0x58, 0x32, 0xd1, 0x55, 0xf3, 0xbc, 0xc0, 0x13,
	0x8f, 0xcc, 0x1d, 0x4c, 0xdf, 0x5e, 0xb9, 0x7d, 0x0d, 0x96, 0x30, 0xa9, 0x8c, 0xf8, 0xc6, 0x1c,
	0xd2, 0xce, 0xc9, 0x84, 0x48, 0x9d, 0xe2, 0x8e, 0x1c, 0x03, 0x54, 0xf5, 0x5a, 0x0a, 0x4e, 0x3b,
	0x07, 0x72, 0x1c, 0xa0, 0x53, 0xdc, 0xcd, 0x7f, 0xf7, 0x61, 0xf6, 0x59, 0x9b, 0x62, 0x23, 0xf5,
	0xd5, 0xfe, 0xdb, 0xc7, 0x00, 0xb9, 0x70, 0xdb, 0x7a, 0x4d, 0xed, 0x96, 0x75, 0xec, 0x13, 0xa0,
	0x8b, 0x2d, 0xfb, 0xc7, 0x30, 0xb8, 0x49, 0x97, 0x33, 0x1a, 0xe7, 0xb8, 0x21, 0xf7, 0x61, 0xd8,
	0x76, 0x2c, 0x5d, 0xcc, 0x48, 0x90, 0x17, 0x30, 0x33, 0x98, 0x0b, 0xeb, 0xcc, 0x8e, 0x6e, 0xb5,
	0x75, 0x8a, 0x95, 0x98, 0x2e, 0xea, 0xcd, 0x96, 0x7d, 0x13, 0x51, 0x72, 0x17, 0xfa, 0xb5, 0x91,
	0xe9, 0x39, 0xf6, 0xab, 0x3e, 0x23, 0xff, 0x47, 0x4a, 0xb4, 0xe9, 0xc9, 0x6d, 0x09, 0x7f, 0x01,
	0x6c, 0x64, 0xed, 0x1c, 0x1a, 0xca, 0xb7, 0x4c, 0x29, 0x94, 0xd9, 0x28, 0x79, 0x01, 0x44, 0x72,
	0x15, 0x40, 0xef, 0x1a, 0x94, 0xc8, 0x2c, 0xfe, 0x75, 0xc7, 0x49, 0x37, 0x92, 0xd1, 0x7d, 0x05,
	0x97, 0xa3, 0xc5, 0xf3, 0x40, 0xad, 0x07, 0xcd, 0x65, 0xfb, 0xf0, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xcf, 0x1b, 0x6b, 0xc8, 0x95, 0x05, 0x00, 0x00,
}
